---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# luria

<!-- badges: start -->

<!-- badges: end -->

This package provides a general framework and data analysis pipeline for conducting fluctuation analysis. Its functions are built around a modification of the [fluxxer.R](https://github.com/barricklab/barricklab/blob/master/fluxxer.R) script written by J. Barrick & D. Deatherage, which in turn calls functions from the [rSalvador](https://github.com/eeeeeric/rSalvador) package to produce mutation rate estimates and comparisons. It should work fine with any microbial system, but was primarily built to work with *Escherichia coli* and *Acinetobacter baylyi* experiments in the Engelstaedter/Letten group --- your mileage with other systems may vary.

<!-- The package has slightly more functionality under the hood, so you should read the function documentation for more information. -->

## Setup

To install the package, run:

``` r
install.packages("devtools")
devtools::install_github("pseudonoma/luria")
```

*luria* works best when you record your data using the bundled Excel workbook template. You can save a copy of the Excel file by running the following line, which saves the template to the current folder:

``` r
get_template(export.to = ".")
```

The first two sheets of the template are usage guides. Once you've read them, you can begin recording your data on the empty sheets. These example sheets are named "Replicate 1" and "Replicate 2", but you can rename them and add more as needed. It's best if the rest of the replicate sheet names keep to a consistent format (e.g. the date of the experiments).

## Use

The pipeline does three things: wrangle the raw data into a *luria*-appropriate structure, analyze the data, and finally plot the mutation rates. These steps can be done individually by running the appropriate functions, but the easiest method is to run the `auto_luria()` wrapper function, as it runs all the necessary functions in order.

To begin, load the package into the library by running:

``` r
library(luria)
```

### The `auto_luria()` function

The wrapper function `auto_luria()` takes a template file containing raw fluctuation analysis data. To run it, do:

``` r
auto_luria(templateData = "template.xlsx",
           extract.mutrates = FALSE,
           export = TRUE, 
           overwrite = FALSE)
```

replacing `template.xlsx` with the path of the template file. The first two sheets in the template, *Example layout* and *Column guide*, are excluded by default, but more sheets can be excluded using the `exclude.sheets` argument. 

The default setting assumes that (a) you filled 60 wells per plate; and (b) *Count* populations were diluted 1:10^5^. To specify different values for these, use the `fill` and `dilution` arguments. Any *Selective* wells missing from the template file are also assumed to have been plated with no observed growth. 

Wrangled intermediate files are exported as CSVs to a folder `\luria_output\` under the current folder, which, if you're working in an R project (you should be), will be the project root. Overwriting is disabled by default out of an overabundance of caution, but can be enabled by using `overwrite = TRUE`. This is useful if you want to process more than one template file by running `auto_luria()` on successive template files.

If you aren't using the standard template for some reason (not recommended), or for more information on other `auto_luria()` arguments and what the data columns mean, read the documentation by calling `?auto_luria` and `?wrangle_raw_data`.

## How the pipeline works

`auto_luria()` calls four functions in order: `wrangle_raw_data()`, `wrangle_clean_data()`, `run_fluxxer()`, and `plot_fluxxer()`. It also runs `extract_mutrates()` at the end if `extract.mutrates = TRUE`. Each of these functions can be run individually if you know what you're doing. You should also read the function documentation, as some function arguments aren't explained here.

When run in order, the functions implicitly connect the data produced back to the template file they started from, i.e. a *project*; subsequent functions try to preserve the filename of that template file in the exported files as a *project name*, appending e.g. `_pooled.csv` to it. Running the functions out of order might interfere with this structure, so do it at your own risk.

`auto_luria()` can be supplied a folder containing multiple template files with `overwrite` also set to `TRUE`. This automatically processes each template file as separate projects, but argument values to e.g. `fill` will be applied identically to all template files -- it only makes sense to run it this way if the experiment parameters were identical across template files.

Functions will optionally save intermediate outputs to a subfolder under `\luria_output\` if `export = TRUE`. `\luria_output\` is created automatically if it doesn't exist, and resides by default in the current directory; this can be changed with the `export.to` argument. Note that `export = FALSE` by default when running the functions individually, and it may be necessary to set `overwrite = TRUE` to allow some functions to save to the necessary folder. Project names can be manually specified by the `save.as` argument wherever a function allows it.

### 1. `wrangle_raw_data()`

This converts the template data into a table with four columns named `strain`, `plate`, `fraction`, and `CFU`. Past this point, the pipeline assumes data inputs are *well-formed*, i.e. it's in this format. The function has default values for `fill` and `dilution` which must be changed to match your experimental design. Additionally, *Selective* wells missing from the data (up to the value of `fill`) are assumed to have been plated but with no growth recorded. 

This function takes one template file at a time; separate template files can be processed by calling the function again with `overwrite = TRUE`.

### 2. `wrangle_clean_data()`

This splits the well-formed table into two: one where all the replicates are pooled together into one "replicate", and another where they're kept separate. The former will ultimately produce the mutation rate estimate you want. If exported, the CSVs are named `*_pooled.csv` and `*_unpooled.csv` respectively. 

This function again takes one CSV or dataframe at a time supplied to `inputData`, but you can process multiple projects individually into the same output folder by setting `overwrite = TRUE`.

### 3. `run_fluxxer()`

This function performs the actual estimation using the Barrick/Deatherage code and the rSalvador package. It produces three CSVs per project: one each for the pooled and unpooled data, with filenames `*.output.csv`; and a third one named `*.comparisons.csv` containing pairwise comparisons between the replicates, with p-values indicating how different they are from each other. Naturally, only unpooled replicates are compared, and setting `comparisons = FALSE` will skip this entirely.

This function takes a list object of pooled/unpooled dataframes returned by the previous function, or a folder containing project pairs of pooled/unpooled CSVs, running the analysis on each of them. It can also take a single dataframe or CSV, in which case it will estimate the mutation rate from that data alone regardless of what it is, including comparisons.

### 4. `plot_fluxxer()`

This function takes the CSVs from the previous function and combines pooled/unpooled data by project into a single plot of mutation rate estimates. By default it exports plots in PNG and PDF format, and returns a ggplot object which can be subsequently modified with the usual ggplot functions.

`plot_fluxxer()` takes a directory containing pooled/unpooled CSV pairs, and will automatically match them by project name. Alternatively, supplying it a single CSV from the previous function will plot just that dataset.

### 5. `extract_mutrates()`

This is a convenience function intended for exporting mutation rate estimates from multiple projects, e.g. for use in modelling; it simply looks in `dataPath` for the relevant files, compiles the mutation rates into a table, and exports it as a CSV and/or RData file depending on the value of `export.method`. `auto_luria()` will run this function if `extract.mutrates = TRUE`.
